<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>false</UseWindowsForms>
    <RootNamespace>Uninstaller.Core</RootNamespace>
    <AssemblyName>Uninstaller.Core</AssemblyName>
    <Platforms>AnyCPU;x64</Platforms>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
